#!/usr/bin/env bash
# setup_dependencies.sh — resolve internal banking_* package versions from
# Artifactory for the requested dependency branch and write them to
# pubspec_overrides.yaml.
#
# Usage:
#   ./.ci/scripts/setup_dependencies.sh [DEPENDENCY_BRANCH]
#
# Required env vars:
#   ARTIFACTORY_URL    — base URL, e.g. https://artifactory.bank.internal
#   ARTIFACTORY_USER   — service account
#   ARTIFACTORY_TOKEN  — API token (do not echo)
#   ARTIFACTORY_REPO   — repo key, e.g. flutter-snapshots
#
# Exits non-zero if any required package has no published version for the branch.

set -euo pipefail

DEPENDENCY_BRANCH="${1:-main}"

: "${ARTIFACTORY_URL:?ARTIFACTORY_URL is required}"
: "${ARTIFACTORY_USER:?ARTIFACTORY_USER is required}"
: "${ARTIFACTORY_TOKEN:?ARTIFACTORY_TOKEN is required}"
: "${ARTIFACTORY_REPO:?ARTIFACTORY_REPO is required}"

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required but not installed on this agent." >&2
  exit 2
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "ERROR: curl is required but not installed on this agent." >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OVERRIDES_FILE="${REPO_ROOT}/pubspec_overrides.yaml"

# Slugify branch name for Artifactory lookup (e.g. feature/foo -> feature-foo).
BRANCH_SLUG="$(echo "${DEPENDENCY_BRANCH}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')"

# TODO: discover this list dynamically from pubspec.yaml by scanning for
# packages under the `banking_` prefix instead of hardcoding.
PACKAGES=(banking_core banking_ui banking_security banking_analytics)

resolve_version() {
  local pkg="$1"
  # Query Artifactory for the latest snapshot for the slug.
  # Expected layout: ${ARTIFACTORY_REPO}/${pkg}/${BRANCH_SLUG}/<version>/
  local api="${ARTIFACTORY_URL%/}/api/search/artifact?name=${pkg}&repos=${ARTIFACTORY_REPO}"
  local response
  response="$(curl -sS --fail \
    -u "${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN}" \
    -H "Accept: application/json" \
    "${api}")" || return 1

  echo "${response}" \
    | jq -r --arg slug "${BRANCH_SLUG}" --arg pkg "${pkg}" '
        .results
        | map(select(.uri | contains("/" + $pkg + "/" + $slug + "/")))
        | sort_by(.uri)
        | last
        | .uri // empty
      ' \
    | awk -F'/' '{ for (i=NF-1; i>0; i--) if ($i ~ /^[0-9]/) { print $i; exit } }'
}

echo "Resolving dependencies for branch: ${DEPENDENCY_BRANCH} (slug: ${BRANCH_SLUG})"

declare -a RESOLVED_LINES=()
MISSING=0
for pkg in "${PACKAGES[@]}"; do
  version="$(resolve_version "${pkg}" || true)"
  if [[ -z "${version}" ]]; then
    echo "MISSING: no Artifactory snapshot for ${pkg} on branch '${DEPENDENCY_BRANCH}'" >&2
    MISSING=1
    continue
  fi
  echo "  ${pkg} => ${version}"
  RESOLVED_LINES+=("  ${pkg}: ${version}")
done

if [[ "${MISSING}" -ne 0 ]]; then
  echo "ERROR: one or more packages have no published version for branch '${DEPENDENCY_BRANCH}'." >&2
  echo "       Publish snapshot artifacts for the missing packages and retry." >&2
  exit 1
fi

{
  echo "# Generated by .ci/scripts/setup_dependencies.sh"
  echo "# Dependency branch: ${DEPENDENCY_BRANCH}"
  echo "dependency_overrides:"
  for line in "${RESOLVED_LINES[@]}"; do
    echo "${line}"
  done
} > "${OVERRIDES_FILE}"

echo "Wrote ${OVERRIDES_FILE}"
